export interface SqlMigration {
  version: number;
  name: string;
  statements: readonly string[];
}

export const COUNTRY_INTEL_MIGRATIONS: readonly SqlMigration[] = [{
  version: 1,
  name: 'country intelligence history',
  statements: [
    `CREATE TABLE country_sources (
      id TEXT PRIMARY KEY,
      region_id TEXT NOT NULL,
      domain TEXT NOT NULL,
      source_type TEXT NOT NULL,
      discovered_at INTEGER NOT NULL,
      verified_at INTEGER,
      verification_status TEXT NOT NULL,
      discovery_method TEXT NOT NULL
    )`,
    'CREATE INDEX idx_country_sources_region ON country_sources(region_id)',
    'CREATE INDEX idx_country_sources_domain ON country_sources(domain)',
    `CREATE TABLE intel_reports (
      context_id TEXT PRIMARY KEY,
      region_id TEXT NOT NULL,
      as_of INTEGER NOT NULL,
      report_json TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      expires_at INTEGER NOT NULL
    )`,
    'CREATE INDEX idx_reports_region_as_of ON intel_reports(region_id, as_of)',
    'CREATE INDEX idx_reports_expires ON intel_reports(expires_at)',
    `CREATE TABLE intel_provider_runs (
      id TEXT PRIMARY KEY,
      report_id TEXT NOT NULL,
      provider TEXT NOT NULL,
      started_at INTEGER NOT NULL,
      finished_at INTEGER,
      status TEXT NOT NULL,
      item_count INTEGER NOT NULL,
      coverage_json TEXT,
      latency_ms INTEGER,
      error_code TEXT,
      FOREIGN KEY(report_id) REFERENCES intel_reports(context_id) ON DELETE CASCADE
    )`,
    'CREATE INDEX idx_provider_runs_report ON intel_provider_runs(report_id)',
    'CREATE INDEX idx_provider_runs_provider_started ON intel_provider_runs(provider, started_at)',
    `CREATE TABLE intel_evidence (
      id TEXT PRIMARY KEY,
      region_id TEXT NOT NULL,
      url TEXT NOT NULL,
      title TEXT,
      publisher TEXT,
      publisher_country TEXT,
      event_country TEXT,
      mentioned_countries_json TEXT,
      source_type TEXT NOT NULL,
      language TEXT,
      published_at INTEGER,
      retrieved_at INTEGER NOT NULL,
      excerpt TEXT,
      content_hash TEXT,
      primary_source INTEGER NOT NULL,
      latency_class TEXT NOT NULL,
      event_cluster_id TEXT,
      excerpt_expires_at INTEGER NOT NULL
    )`,
    'CREATE INDEX idx_evidence_region_published ON intel_evidence(region_id, published_at)',
    'CREATE INDEX idx_evidence_retrieved ON intel_evidence(retrieved_at)',
    'CREATE INDEX idx_evidence_excerpt_expires ON intel_evidence(excerpt_expires_at)',
    `CREATE TABLE intel_events (
      id TEXT PRIMARY KEY,
      report_id TEXT,
      region_id TEXT NOT NULL,
      type TEXT NOT NULL,
      title TEXT NOT NULL,
      occurred_at INTEGER,
      location_json TEXT,
      actors_json TEXT NOT NULL,
      targets_json TEXT NOT NULL,
      evidence_count INTEGER NOT NULL,
      independent_source_count INTEGER NOT NULL,
      primary_source_count INTEGER NOT NULL,
      first_seen_at INTEGER NOT NULL,
      last_seen_at INTEGER NOT NULL,
      confidence TEXT NOT NULL,
      expires_at INTEGER NOT NULL,
      FOREIGN KEY(report_id) REFERENCES intel_reports(context_id) ON DELETE SET NULL
    )`,
    'CREATE INDEX idx_events_region_occurred ON intel_events(region_id, occurred_at)',
    'CREATE INDEX idx_events_report ON intel_events(report_id)',
    'CREATE INDEX idx_events_expires ON intel_events(expires_at)',
    `CREATE TABLE intel_event_evidence (
      event_id TEXT NOT NULL,
      evidence_id TEXT NOT NULL,
      PRIMARY KEY(event_id, evidence_id),
      FOREIGN KEY(event_id) REFERENCES intel_events(id) ON DELETE CASCADE,
      FOREIGN KEY(evidence_id) REFERENCES intel_evidence(id) ON DELETE CASCADE
    )`,
    'CREATE INDEX idx_event_evidence_evidence ON intel_event_evidence(evidence_id)',
    `CREATE TABLE intel_poll_observations (
      id TEXT PRIMARY KEY,
      region_id TEXT NOT NULL,
      pollster TEXT NOT NULL,
      field_start INTEGER,
      field_end INTEGER,
      observed_at INTEGER NOT NULL,
      sample_size INTEGER,
      population TEXT,
      mode TEXT,
      question TEXT NOT NULL,
      responses_json TEXT NOT NULL,
      source_url TEXT NOT NULL,
      evidence_id TEXT,
      FOREIGN KEY(evidence_id) REFERENCES intel_evidence(id) ON DELETE SET NULL
    )`,
    'CREATE INDEX idx_polls_region_observed ON intel_poll_observations(region_id, observed_at)',
    `CREATE TABLE intel_daily_metrics (
      region_id TEXT NOT NULL,
      observed_at INTEGER NOT NULL,
      metric_key TEXT NOT NULL,
      current_value REAL NOT NULL,
      window TEXT NOT NULL,
      baseline_json TEXT,
      anomaly_z REAL,
      direction TEXT NOT NULL,
      expires_at INTEGER NOT NULL,
      PRIMARY KEY(region_id, observed_at, metric_key)
    )`,
    'CREATE INDEX idx_daily_metrics_region_observed ON intel_daily_metrics(region_id, observed_at)',
    'CREATE INDEX idx_daily_metrics_expires ON intel_daily_metrics(expires_at)',
    `CREATE TABLE intel_calendar_events (
      id TEXT PRIMARY KEY,
      region_id TEXT NOT NULL,
      event_at INTEGER NOT NULL,
      date TEXT NOT NULL,
      title TEXT NOT NULL,
      type TEXT NOT NULL,
      official INTEGER NOT NULL,
      related_countries_json TEXT,
      source_url TEXT NOT NULL,
      evidence_id TEXT,
      FOREIGN KEY(evidence_id) REFERENCES intel_evidence(id) ON DELETE SET NULL
    )`,
    'CREATE INDEX idx_calendar_region_event ON intel_calendar_events(region_id, event_at)',
  ],
},
{
  version: 2,
  name: 'metric observations for baseline-eligible history',
  statements: [
    `CREATE TABLE intel_metric_observations (
      region_id TEXT NOT NULL,
      metric_key TEXT NOT NULL,
      metric_kind TEXT NOT NULL,
      window TEXT NOT NULL,
      bucket_start INTEGER,
      bucket_end INTEGER,
      observed_at INTEGER NOT NULL,
      current_value REAL NOT NULL,
      origin TEXT NOT NULL,
      baseline_eligible INTEGER NOT NULL,
      provider_ids_json TEXT,
      evidence_ids_json TEXT,
      expires_at INTEGER NOT NULL,
      PRIMARY KEY(region_id, metric_key, window, bucket_end, origin, observed_at)
    )`,
    'CREATE INDEX idx_metric_obs_region_key_bucket ON intel_metric_observations(region_id, metric_key, bucket_end)',
    'CREATE INDEX idx_metric_obs_region_observed ON intel_metric_observations(region_id, observed_at)',
    'CREATE INDEX idx_metric_obs_expires ON intel_metric_observations(expires_at)',
  ],
},
{
  version: 3,
  name: 'evidence details, context links, source states and change history',
 statements: [
    `CREATE TABLE intel_evidence_details (
     evidence_id TEXT PRIMARY KEY,
      provider_id TEXT NOT NULL,
      provider_item_id TEXT NOT NULL,
      source_record_url TEXT NOT NULL,
      content_kind TEXT NOT NULL,
      language TEXT,
      blocks_json TEXT NOT NULL,
      structured_json TEXT,
      occurred_at INTEGER,
      published_at INTEGER,
      updated_at INTEGER,
      retrieved_at INTEGER NOT NULL,
      valid_from INTEGER,
      valid_until INTEGER,
      time_basis TEXT NOT NULL,
      geography_basis TEXT NOT NULL,
      source_status TEXT NOT NULL,
      content_truncated INTEGER NOT NULL,
      expires_at INTEGER NOT NULL
    )`,
    'CREATE INDEX idx_evidence_details_provider ON intel_evidence_details(provider_id, provider_item_id)',
   'CREATE INDEX idx_evidence_details_expires ON intel_evidence_details(expires_at)',
    `CREATE TABLE intel_context_evidence (
     context_id TEXT NOT NULL,
      evidence_id TEXT NOT NULL,
      sort_key TEXT NOT NULL,
      PRIMARY KEY(context_id, evidence_id)
    )`,
   'CREATE INDEX idx_context_evidence_evidence ON intel_context_evidence(evidence_id)',
    `CREATE TABLE intel_source_states (
     source_id TEXT PRIMARY KEY,
      last_checked_at INTEGER,
      last_success_at INTEGER,
      provider_updated_at INTEGER,
      last_error_code TEXT,
      etag TEXT,
      last_modified TEXT,
      retry_at INTEGER,
      cursor TEXT,
      window_json TEXT
    )`,
    `CREATE TABLE intel_context_changes (
      id TEXT PRIMARY KEY,
      context_id TEXT NOT NULL,
      observed_at INTEGER NOT NULL,
      change_kind TEXT NOT NULL,
      evidence_id TEXT,
      summary_json TEXT
    )`,
    'CREATE INDEX idx_context_changes_context ON intel_context_changes(context_id, observed_at)',
  ],
},
{
  version: 4,
  name: 'scheduled hot list observations',
  statements: [
    'CREATE TABLE intel_hot_observations (source_id TEXT NOT NULL, topic_id TEXT NOT NULL, region_id TEXT NOT NULL, observed_at INTEGER NOT NULL, rank INTEGER, hot TEXT, pinned INTEGER NOT NULL DEFAULT 0, title TEXT NOT NULL, url TEXT NOT NULL, upstream_updated_at INTEGER, expires_at INTEGER NOT NULL, PRIMARY KEY (source_id, topic_id, observed_at))',
    'CREATE INDEX idx_hot_obs_source_observed ON intel_hot_observations (source_id, observed_at)',
    'CREATE INDEX idx_hot_obs_expires ON intel_hot_observations (expires_at)',
  ],
}];
