import { describe, expect, test } from 'bun:test';
import { SEARCH_WEB_INPUT_SHAPE, SearchWebRequestSchema, buildSearchWebCacheKey, searchWebWithFormats } from './search_web_formats.js';
describe('search_web formats orchestration',()=>{
  test('legacy no-format path preserves provider object by identity',async()=>{ const provider={items:[{title:'A',url:'https://e/a',snippet:'s'}],count:1,source:'web'}; let calls=0; const r=await searchWebWithFormats({query:'x'},{searchYahooWeb:async()=>provider,scrapeUrl:async()=>{calls++; throw new Error('no');}} as any); expect(r).toBe(provider); expect(calls).toBe(0); });
  test('formats activates scraping and defaults to top five',async()=>{ const provider={items:Array.from({length:7},(_,i)=>({title:`R${i}`,url:`https://e/${i}`,snippet:`s${i}`})),count:7,source:'web'}; let calls=0; const r=await searchWebWithFormats({query:'x',formats:['markdown']},{searchYahooWeb:async()=>provider,scrapeUrl:async({url}:any)=>{calls++; return {content:`# ${url}\n\nfull body with enough characters 123456789012345678901234567890`};}} as any); expect(r.items).toHaveLength(5); expect(calls).toBe(5); expect(r.items[0].markdown).toContain('full body'); expect(r.items[0].html).toBeUndefined(); });
  test('requested structured formats do not leak unrelated payloads',async()=>{ const r=await searchWebWithFormats({query:'t',formats:['tables','images'],limit:1},{searchYahooWeb:async()=>({items:[{title:'T',url:'https://e/t'}],count:1,source:'web'}),scrapeUrl:async()=>({content:'# hidden',html:'<p>x</p>',tables:[{headers:['A'],rows:[{A:'1'}]}],images:[{url:'x'}]})} as any); expect(r.items[0].tables).toHaveLength(1); expect(r.items[0].images).toHaveLength(1); expect(r.items[0].markdown).toBeUndefined(); expect(r.items[0].html).toBeUndefined(); });
  test('one scrape failure preserves sibling search results',async()=>{ const r=await searchWebWithFormats({query:'x',formats:['markdown'],limit:2},{searchYahooWeb:async()=>({items:[{title:'A',url:'https://e/a',snippet:'a'},{title:'B',url:'https://e/b',snippet:'b'}],count:2,source:'web'}),scrapeUrl:async({url}:any)=>{if(url.endsWith('/a')) throw new Error('blocked'); return {content:'# B\n\nusable body with enough characters 123456789012345678901234567890'};}} as any); expect(r.items[0].scrapeError).toContain('blocked'); expect(r.items[1].markdown).toContain('usable body'); });
  test('shared schema/cache key partition formats',()=>{ expect(SearchWebRequestSchema.safeParse({query:'x',formats:['markdown','tables']}).success).toBe(true); expect(SearchWebRequestSchema.safeParse({query:'x',formats:['bogus']}).success).toBe(false); expect(SEARCH_WEB_INPUT_SHAPE.formats).toBeDefined(); expect(buildSearchWebCacheKey({query:'x'})).not.toBe(buildSearchWebCacheKey({query:'x',formats:['markdown']})); });
});
